/**
 * Generates src/lib/brands.generated.ts (pure data) from the simple-icons
 * package. The matching and search logic lives in src/lib/brands.ts.
 *
 * The brand glyphs are bundled, never fetched: the app must stay fully offline
 * and must not tell a third party what anyone buys (context/01, principle 3).
 * Only the brands listed below are extracted, so the bundle carries ~30 paths
 * instead of the package's 3400.
 *
 * Run after editing BRANDS:
 *   node scripts/generate-brands.mjs
 *
 * Keywords are matched as whole words against the normalized (unaccented,
 * lowercased) description, so they are written unaccented here. Avoid words
 * that are ordinary French: "orange" (the fruit), "boulanger" (the baker),
 * "action" (the noun) would all fire on innocent expenses.
 */
import { writeFileSync } from 'node:fs'
import * as si from 'simple-icons'

const BRANDS = [
  // Courses
  { key: 'siCarrefour', keywords: ['carrefour', 'carouf'], emoji: '🛒' },
  { key: 'siLidl', keywords: ['lidl'], emoji: '🛒' },
  { key: 'siAldinord', name: 'Aldi', keywords: ['aldi'], emoji: '🛒' },
  { key: 'siIntermarche', keywords: ['intermarche'], emoji: '🛒' },
  { key: 'siAuchan', keywords: ['auchan'], emoji: '🛒' },
  { key: 'siMonoprix', keywords: ['monoprix', 'monop'], emoji: '🛒' },
  { key: 'siFranprix', keywords: ['franprix'], emoji: '🛒' },
  { key: 'siCora', keywords: ['cora'], emoji: '🛒' },

  // Restauration
  { key: 'siBurgerking', keywords: ['burger king', 'burgerking'], emoji: '🍔' },
  { key: 'siMcdonalds', keywords: ['mcdo', 'macdo', 'mcdonalds', 'mcdonald', 'mc do'], emoji: '🍔' },
  { key: 'siKfc', keywords: ['kfc'], emoji: '🍔' },
  { key: 'siStarbucks', keywords: ['starbucks', 'starbuck'], emoji: '☕' },
  { key: 'siUbereats', keywords: ['uber eats', 'ubereats'], emoji: '🍽️' },
  { key: 'siDeliveroo', keywords: ['deliveroo'], emoji: '🍽️' },
  { key: 'siJusteat', keywords: ['just eat', 'justeat'], emoji: '🍽️' },

  // Transport et voyage
  { key: 'siUber', keywords: ['uber'], emoji: '🚕' },
  { key: 'siSncf', keywords: ['sncf'], emoji: '🚆' },
  { key: 'siAirfrance', keywords: ['air france', 'airfrance'], emoji: '✈️' },
  { key: 'siRyanair', keywords: ['ryanair'], emoji: '✈️' },
  { key: 'siEasyjet', keywords: ['easyjet', 'easy jet'], emoji: '✈️' },
  { key: 'siAirbnb', keywords: ['airbnb'], emoji: '🏨' },
  { key: 'siShell', keywords: ['shell'], emoji: '⛽' },

  // Magasins
  { key: 'siIkea', keywords: ['ikea'], emoji: '🛋️' },
  { key: 'siFnac', keywords: ['fnac'], emoji: '🔌' },
  { key: 'siDarty', keywords: ['darty'], emoji: '🔌' },
  { key: 'siLeroymerlin', keywords: ['leroy merlin', 'leroymerlin'], emoji: '🛠️' },
  { key: 'siCastorama', keywords: ['castorama', 'casto'], emoji: '🛠️' },
  { key: 'siZara', keywords: ['zara'], emoji: '👕' },
  { key: 'siUniqlo', keywords: ['uniqlo'], emoji: '👕' },
  { key: 'siNike', keywords: ['nike'], emoji: '👟' },
  { key: 'siAdidas', keywords: ['adidas'], emoji: '👟' },

  // Abonnements et loisirs
  { key: 'siNetflix', keywords: ['netflix'], emoji: '📺' },
  { key: 'siSpotify', keywords: ['spotify'], emoji: '🎵' },
  { key: 'siDeezer', keywords: ['deezer'], emoji: '🎵' },
  { key: 'siYoutube', keywords: ['youtube'], emoji: '📺' },
  { key: 'siTwitch', keywords: ['twitch'], emoji: '🎮' },
  { key: 'siPlaystation', keywords: ['playstation', 'psn'], emoji: '🎮' },
  { key: 'siSteam', keywords: ['steam'], emoji: '🎮' },
  { key: 'siApple', keywords: ['apple'], emoji: '🖥️' },
]

const entries = BRANDS.map(({ key, name, keywords, emoji }) => {
  const icon = si[key]
  if (!icon) throw new Error(`simple-icons has no ${key} (it may have been removed)`)
  return {
    id: key.slice(2).toLowerCase(),
    name: name ?? icon.title,
    hex: icon.hex,
    path: icon.path,
    keywords,
    emoji,
  }
})

const file = `/**
 * Brand marks for expenses. GENERATED by scripts/generate-brands.mjs from the
 * simple-icons package: do not edit by hand, edit the script and re-run it.
 *
 * Bundled rather than fetched, so the app stays offline-first and no third
 * party ever learns what anyone buys. The glyphs are single-colour paths on a
 * 24x24 viewBox, drawn in the brand's own colour. They are the trademarks of
 * their owners, used here only to label an expense in a private instance.
 */
export interface BrandEntry {
  id: string
  name: string
  /** Brand colour, without the leading '#'. */
  hex: string
  /** SVG path on a 24x24 viewBox. */
  path: string
  /** Whole-word triggers, unaccented and lowercased. */
  keywords: string[]
  /** Kept alongside the logo so lists that show emojis stay lively. */
  emoji: string
}

export const BRANDS: BrandEntry[] = ${JSON.stringify(entries, null, 2)}
`

writeFileSync(new URL('../src/lib/brands.generated.ts', import.meta.url), file)
console.log(`Wrote ${entries.length} brands to src/lib/brands.generated.ts`)
