"""init groups and operations

Revision ID: c2dc57cd3548
Revises: 
Create Date: 2026-07-13 21:20:43.469475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2dc57cd3548'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('share_code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_share_code'), 'groups', ['share_code'], unique=True)
    op.create_table('operations',
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('lamport', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_operations_group_id'), 'operations', ['group_id'], unique=False)
    op.create_index('ix_operations_group_seq', 'operations', ['group_id', 'seq'], unique=False)
    op.create_index(op.f('ix_operations_op_id'), 'operations', ['op_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_op_id'), table_name='operations')
    op.drop_index('ix_operations_group_seq', table_name='operations')
    op.drop_index(op.f('ix_operations_group_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_groups_share_code'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
